version: "3.0"

services:
 front:
  build: ./front-end
  ports:
   - "8081:8081"

 back:
  build: ./back-end/liargame
  ports:
   - "5000:5000"

 redis:
  image: redis:6.2.4-alpine
  container_name: redis
  ports:
   - "6379:6379"
