version: "3.0"

services:
 front:
  build: ./front-end
  ports:
   - "8081:8081"
  volumes:
   - /var/www/html:/app

 back:
  build: ./back-end/liargame
  ports:
   - "5000:5000"
  environment:
   SPRING_REDIS_HOST: "redis"
   server.address: 0.0.0.0
  depends_on:
   - redis
  networks:
   - tempnet

 redis:
  image: redis:6.2.4-alpine
  container_name: redis
  ports:
   - "6379:6379"
  networks:
   - tempnet

networks:
 tempnet:
