version: "3.0"

services:
 front:
  build:
   context: /home/ubuntu/***REMOVED***/front-end
  ports:
   - 8081:8081

 db:
  image: mysql:8.0
  environment:
   MYSQL_ROOT_PASSWORD: ssafy
   MYSQL_DATABASE: test
   MYSQL_USER: root
   MYSQL_PASSWORD: ssafy
  ports:
   - "3306:3306"

 back:
  build:
   context: /home/ubuntu/***REMOVED***/back-end/liargame
  ports:
   - "5000:5000"
  depends_on:
   - db