version: "3.0"

services:
 mysql:
  image: mariadb:10.4.20
  container_name: mysql
  restart: always
  ports:
   - "3306:3306"
  environment:
   MYSQL_DATABASE: test
   MYSQL_ROOT_PASSWORD: ssafy
   MYSQL_USER: root
   MYSQL_PASSWORD: ssafy
  volumes:
   - ./mysql/data:/var/lib/mysql
   - ./mysql/config:/etc/mysql/conf.d
  privileged: true
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  networks:
   - tempnet
  
 front:
  build: ./front-end
  ports:
   - "8081:8081"
  volumes:
   - /var/www/html:/app

 back:
  build: ./back-end/liargame
  ports:
   - "5000:5000"
  environment:
   SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/test?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true"
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: ssafy
   SPRING_REDIS_HOST: "redis"
   server.address: 0.0.0.0
  depends_on:
   - redis
   - mysql
  networks:
   - tempnet

 redis:
  image: redis:6.2.4-alpine
  container_name: redis
  volumes:
   - ./redis/redis-data:/data
  ports:
   - "6379:6379"
  networks:
   - tempnet

networks:
 tempnet:
