FROM openjdk:11-jdk

COPY build/libs/*.jar liargame.jar

#EXPOSE 5000
#CMD ["java", "-jar", "./*.jar"]
#ENTRYPOINT ["java", "-jar", "./build/libs/liargame-0.0.1-SNAPSHOT.jar"]
ENTRYPOINT ["java","-jar","/liargame.jar"]
